import type { Metadata } from "next";
import Link from "next/link";
import { wrapItUp } from "@/data/wrap-it-up";

const description = "How Wrap It Up! handles local progress, captures, beta services, packaged SDKs, and support information.";
export const metadata: Metadata = {
  title: "Wrap It Up! Privacy Policy",
  description,
  alternates: { canonical: `${wrapItUp.path}/privacy` },
  openGraph: { title: "Wrap It Up! Privacy Policy", description, url: `${wrapItUp.path}/privacy`, images: [wrapItUp.artwork] },
};

export default function WrapItUpPrivacyPage() {
  return (
    <>
      <div className="project-page-header">
        <span className="eyebrow section-label">WRAP IT UP! / PRIVACY</span>
        <h1>Privacy policy.</h1>
        <p>For Wrap It Up!, published by Jade Laurence Empleo (SyntaxSurge).</p>
        <p className="app-small-copy">Effective October 2, 2026 · Current distributed beta {wrapItUp.version}; includes guidance for earlier build 4</p>
      </div>
      <div className="app-copy app-policy">
        <section><h2>Gameplay and local storage</h2><p>Wrap It Up! is a single-player gift-wrapping game. It does not require a player account. Progress, in-game currency, inventory, wrapping history, and settings are stored in the app&apos;s private storage on your device. The game has no cloud-save service, custom gameplay backend, or gameplay analytics integration.</p><p>Core gameplay works offline. Local data remains until you remove it through your device&apos;s app-data controls or delete the app. A local save is not recoverable from a publisher server after deletion or a move to another device.</p></section>
        <section><h2>Captures you choose to share</h2><p>The Capture action creates a PNG image in app-private storage. On Android, choosing Share gives your selected destination temporary access to that image through the system share chooser. The game does not automatically upload captures. The recipient app handles a shared image under its own privacy terms.</p><p>The game does not request camera, microphone, photo-library, location, contacts, or general media-storage access for this feature. Images you save or share outside the app may remain there after you delete the game.</p></section>
        <section><h2>Android SDKs and network data</h2><p>The Android package includes Google Mobile Ads, Google&apos;s User Messaging Platform, and Unity Ads, AppLovin, and Pangle advertising libraries. Rewarded ads are disabled in beta {wrapItUp.version}. In build 4, packaged SDK startup components can run independently of the game&apos;s disabled ad buttons. Offline gameplay therefore does not mean these components are network-free.</p><p>These services may collect or share IP addresses, approximate location derived from an IP address, device or app identifiers, app interactions, and diagnostic information for advertising services, analytics, security, and fraud prevention. The exact activity depends on the SDK and its configuration. The Android app omits the advertising-ID permission; that alone does not prevent other identifiers or network metadata.</p><p>The distributed Android beta {wrapItUp.version} blocks the advertising libraries&apos; automatic startup entry points as well as the game&apos;s ad flow. This does not change the behavior of a previously installed build 4. Any future advertising-enabled version must pass the publisher&apos;s privacy and consent review, and this policy will be updated for that release.</p><p>For provider details and privacy choices, see <a href="https://developers.google.com/admob/android/privacy/play-data-disclosure" target="_blank" rel="noopener noreferrer">Google Mobile Ads data disclosures</a>, <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google&apos;s privacy policy</a>, <a href="https://unity.com/legal/game-player-and-app-user-privacy-policy" target="_blank" rel="noopener noreferrer">Unity&apos;s player privacy policy</a>, <a href="https://legal.applovin.com/privacy/" target="_blank" rel="noopener noreferrer">AppLovin&apos;s privacy policy</a>, and <a href="https://www.pangleglobal.com/privacy/enduser-en" target="_blank" rel="noopener noreferrer">Pangle&apos;s end-user privacy policy</a>.</p></section>
        <section><h2>Purchases and iOS</h2><p>Real-money in-app purchases are disabled in the distributed beta. Android and iOS packages include RevenueCat purchase libraries, but the game does not configure a purchase session while that feature is disabled. There is no active purchase flow or publisher purchase account in this beta. iOS does not have an active rewarded-ad provider.</p><p>Apple and Google independently handle installation, updates, store accounts, and beta testing. TestFlight feedback and crash information you share are handled through Apple&apos;s services and may be made available to the developer. Review <a href="https://www.apple.com/legal/privacy/" target="_blank" rel="noopener noreferrer">Apple&apos;s privacy policy</a> and the store&apos;s beta-testing notices.</p></section>
        <section><h2>Support messages</h2><p>If you contact support, we receive the information you choose to send, such as your contact details, device information, message, and attachments. We use it to reply, investigate the reported issue, and maintain necessary support records. Please do not send passwords or sensitive personal information. The email or messaging service you choose also processes your message under its own terms.</p><p>Contact us to request access, correction, or deletion of information you sent to support. We retain support information only as needed to handle the request and meet applicable obligations. We cannot delete an image or message held independently by another recipient or platform.</p></section>
        <section><h2>This website</h2><p>These pages do not include a contact form, advertising tracker, or visitor analytics integration. Your theme preference may be saved in your browser&apos;s local storage. The hosting server and Cloudflare may process standard request information, including IP address, browser information, requested URLs, and timestamps, to deliver and protect the website. External links open services that have their own privacy policies.</p></section>
        <section><h2>Children and family use</h2><p>The game&apos;s local play does not ask for a name, age, email address, or player account. A store age rating is not a guarantee about third-party SDK data handling. Parents and guardians can contact the developer with privacy questions and should supervise beta enrollment and external sharing.</p></section>
        <section><h2>Your choices and policy updates</h2><p>You can play core gameplay offline, choose whether to share a capture or send feedback, and remove local app data. Android app-storage controls can clear the local save. On iOS, Delete App removes its app data; Offload App preserves documents and data. Previously exported or shared files remain at their destinations.</p><p>We update this policy when the app&apos;s data handling changes, including before enabling advertising or purchases in a future release. The effective date and beta version above identify the scope of this policy.</p></section>
        <section><h2>Contact</h2><p>For privacy questions or requests, email Jade Laurence Empleo (SyntaxSurge) at <a href={wrapItUp.contactUrl}>{wrapItUp.supportEmail}</a>, or visit <Link href={`${wrapItUp.path}/support`}>Wrap It Up! support</Link>.</p></section>
      </div>
    </>
  );
}
